version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: ms-boilerplate
    restart: always
    env_file:
    - .env
    ports:
      # Exposes application port.
    - "5000:5000"
